Comment out Python workflow configuration

diff --git a/.github/workflows/python.yml b/.github/workflows/python.yml
--- a/.github/workflows/python.yml
+++ b/.github/workflows/python.yml
@@ -1,46 +1,46 @@
-name: Python
+# name: Python
 
-on:
-  push:
-    branches: ["main"]
-  pull_request:
-    branches: ["main"]
-  schedule:
-    - cron: "0 */12 * * *" # Executa a cada 12 horas
-  workflow_dispatch:
+# on:
+#   push:
+#     branches: ["main"]
+#   pull_request:
+#     branches: ["main"]
+#   schedule:
+#     - cron: "0 */12 * * *" # Executa a cada 12 horas
+#   workflow_dispatch:
 
-jobs:
-  build:
-    runs-on: ubuntu-latest
+# jobs:
+#   build:
+#     runs-on: ubuntu-latest
 
-    steps:
-      - name: Checkout código
-        uses: actions/checkout@v4
+#     steps:
+#       - name: Checkout código
+#         uses: actions/checkout@v4
 
-      - name: Configurar Python
-        uses: actions/setup-python@v4
-        with:
-          python-version: "3.12"
+#       - name: Configurar Python
+#         uses: actions/setup-python@v4
+#         with:
+#           python-version: "3.12"
 
-      - name: Instalar dependências do Python
-        run: |
-          python -m pip install --upgrade pip
-          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
+#       - name: Instalar dependências do Python
+#         run: |
+#           python -m pip install --upgrade pip
+#           if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
 
-      - name: Executar script Python
-        env:
-          URL_API: ${{ secrets.URL_API }}
-          URL_APP: ${{ secrets.URL_APP }}
-          URL_X: ${{ secrets.URL_X }}
-          TOKEN: ${{ secrets.TOKEN }}
-          USER_ID: ${{ secrets.USER_ID }}
-          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
-          USER_AGENT: ${{ secrets.USER_AGENT }}
-        run: python app.py
+#       - name: Executar script Python
+#         env:
+#           URL_API: ${{ secrets.URL_API }}
+#           URL_APP: ${{ secrets.URL_APP }}
+#           URL_X: ${{ secrets.URL_X }}
+#           TOKEN: ${{ secrets.TOKEN }}
+#           USER_ID: ${{ secrets.USER_ID }}
+#           ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
+#           USER_AGENT: ${{ secrets.USER_AGENT }}
+#         run: python app.py
         
-      - name: Fazer upload da captura de tela
-        if: success() || failure()
-        uses: actions/upload-artifact@v4
-        with:
-          name: screenshot
-          path: screen.png
+#       - name: Fazer upload da captura de tela
+#         if: success() || failure()
+#         uses: actions/upload-artifact@v4
+#         with:
+#           name: screenshot
+#           path: screen.png
